config/routes.rb
RestaurantPos::Application.routes.draw do

  root to: 'static_pages#welcome'

  resources :restaurants do
    resources :dishes
  end

end

app/models/dish.rb
class Dish < ActiveRecord::Base

	belongs_to :restaurant

	validates :name, presence: true

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

	has_many :dishes, dependent: :destroy

	validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def index
  end

  def show
  	@dish = Dish.find params[:id]
  end

  def new
  	@restaurant = Restaurant.find params[:restaurant_id]
  	@dish = Dish.new

    respond_to do |format|
      format.html { render 'new' }
      format.js { render 'new.js.erb' }
    end
  end

  def create
  	@dish = Dish.new dish_params

  	if @dish.save
  		redirect_to restaurant_url(@dish.restaurant_id)
  	else
  		render 'new'
  	end
  end

  def destroy
  end

  def edit
  	@dish = Dish.find params[:id]
  	@restaurant = @dish.restaurant

    respond_to do |format|
      format.html { render 'edit' }
      format.js { render 'edit.js.erb' }
    end
  end

  def update
  	@dish = Dish.find params[:id]
  	if @dish.update(dish_params)
  		redirect_to restaurant_url(@dish.restaurant_id)
  	else
  		render 'edit'
  	end
  end

  private

  def dish_params
    params.require(:dish).permit(:restaurant_id, :name, :price, :image_url)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all

    if params[:city] && params[:name]
      @restaurants = Restaurant.where("city LIKE ?", "%#{params[:city]}%")
      @restaurants = Restaurant.where("name LIKE ?", "%#{params[:name]}%")
    elsif params[:city]
      @restaurants = Restaurant.where("city LIKE ?", "%#{params[:city]}%")
    elsif params[:name]
      @restaurants = Restaurant.where("name LIKE ?", "%#{params[:name]}%")
    end
  end

  def show
    @dishes = @restaurant.dishes.to_a
  end

  def new
    @restaurant = Restaurant.new

    respond_to do |format|
      format.html { render action: 'new' }
      format.js { render 'new.js.erb' }
    end
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.js { render 'create.js.erb' }
      else
        format.html { render action: 'new' }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.js { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end

  private
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :city)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def welcome
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/dishes/_dish.html.erb
<!-- <span class="item well">
		<div><strong><%= link_to dish.name, restaurant_dish_url(dish.restaurant_id, dish.id) %></strong></div>
		<div><em><%= dish.price %></em></div>
		<% if session[:user_id] %>
		<% end %>
</span>
 -->
<div class="item">
	<%= link_to dish.name, restaurant_dish_url(dish.restaurant_id, dish.id), class: 'dish-link' %>
	<%= link_to image_tag(dish.image_url), restaurant_dish_url(dish.restaurant_id, dish.id) %>
</div>

app/views/dishes/_form.html.erb
<%= form_for [restaurant, dish] do |f| -%>
	<% if dish.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

	    <ul>
	    <% dish.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>
	<div class="field">
	  <%= f.label :name %><br>
	  <%= f.text_field :name %>
	</div>
	<div class="field">
	  <%= f.label :price %><br>
	  <%= f.text_field :price %>
	</div>
	<div class="field">
	  <%= f.label :image_url %><br>
	  <%= f.text_field :image_url %>
	</div>
	<%= f.hidden_field :restaurant_id, value: restaurant.id %>
	<div>
	  <%= f.submit %>
	</div>
<% end -%>

app/views/dishes/create.html.erb
<h1>Dishes#create</h1>
<p>Find me in app/views/dishes/create.html.erb</p>

app/views/dishes/destroy.html.erb
<h1>Dishes#destroy</h1>
<p>Find me in app/views/dishes/destroy.html.erb</p>

app/views/dishes/edit.js.erb
$('.form-spot').html('<%= j render("form", dish: @dish, restaurant: @restaurant) %>');

app/views/dishes/index.html.erb
<h1>Dishes#index</h1>
<p>Find me in app/views/dishes/index.html.erb</p>

app/views/dishes/new.js.erb
$('.form-spot').html('<%= j render("form", restaurant: @restaurant, dish: @dish) %>');

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @dish.name %> from <%= @dish.restaurant.name %></h1>

<%= link_to 'Back', restaurant_path(@dish.restaurant) %>
<p>
  <strong>Name:</strong>
  <%= @dish.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @dish.price %>
</p>

<div class="form-spot">
	<%= link_to 'Edit', edit_restaurant_dish_path(@dish.restaurant, @dish), remote: true %>
</div>

app/views/dishes/update.html.erb
<h1>Dishes#update</h1>
<p>Find me in app/views/dishes/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestaurantPos</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(restaurant, remote: true) do |f| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-field' %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city, class: 'form-field' %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: 'form-field' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<span class="item well">
		<div><strong><%= link_to restaurant.name, restaurant %></strong></div>
		<div><em><%= restaurant.address %></em></div>
		<img src="<%= restaurant.image_url %>">
		<% if session[:user_id] %>
			<%= link_to 'Edit', edit_restaurant_path(restaurant) %>
			<%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>
</span>

app/views/restaurants/create.js.erb
$('.restaurant-list').append('<%= j render("restaurant", restaurant: @restaurant) %>');
$('.form-field').val('');

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Listing restaurants</h1>

<div class="restaurant-list">
	<%= render @restaurants %>
</div>

<div class="form-spot">
  <%= link_to 'New Restaurant', new_restaurant_url, remote: true %>
</div>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/new.js.erb
$('.form-spot').replaceWith('<%= j render("form", restaurant: @restaurant) %>');

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
	Dishes at <em><%= @restaurant.name %></em> - <%= @restaurant.address %>
	<span class="actions">
		<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> <br>
		<%= link_to 'Back', restaurants_path %>
	</span>
</h1>


<% dish = @dishes.pop %>
<img id="top-dish" src="<%= "#{dish.image_url}" %>">


<div id="container">
	<% @dishes.each do |dish| %>
		<%= render '/dishes/dish', dish: dish %>
	<% end %>
</div>

<div class="form-spot">
	<%= link_to 'Add a Dish', new_restaurant_dish_url(@restaurant), remote: true %>
</div>

app/views/static_pages/welcome.html.erb
<h1>
	APPetite
	<span class="actions">
		<%= link_to 'Login', '#' %> <br>
		<%= link_to 'Signup', '#' %>
	</span>
</h1>
<p>This is a tagline for appetite. It is witty and enticing. Perhaps, it even includes a call to action.</p>


<p>Search by...</p>
<form action="<%= restaurants_url %>" method="get" class="form">
  <%= label_tag :name, 'Name' %>
	<%= text_field_tag :name %>
	<%= submit_tag "Go!", id: "search-btn", name: nil %>
</form>

<span>Or...</span>
<form action="<%= restaurants_url %>" method="get" class="form">
  <%= label_tag :city, 'City' %>
	<%= text_field_tag :city %>
	<%= submit_tag "Go!", id: "search-btn", name: nil %>
</form>